### ISSUE TITLE
Mutation function

### ISSUE THREAD

**Issue by mcortes-lopez** [mritchielab/FLAMES#10]
Hi, 
I was trying to run the mutation function (`sc_mutations`), just changing the coverage min to 5, but I keep having the following error after some chromosomes: 

`Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ZeroDivisionError: float division by zero
Calls: sc_mutations ... do.call -> <Anonymous> -> <Anonymous> -> py_call_impl`

Given that there is not much information in the vignette, I was wondering if you would have a suggestion on how to debug this error?  
Why is it 100 the minimum for the coverage used?

**Comment by ChangqingW** [comment]
Using 100 as the default threshold is probably because Luyi was working with deeper sequencing experiments, changing it to 5 should be fine. Could you try running the Python functions directly and see if it produce a more useful error message? `sc_mutations` is using the Python function in `inst/Python/sc_mutations.py`
